Development/network cleanup
rdkcentral/ThunderNanoServices pull request #207
Opened 2020-09-03 10:13 UTC by pwielders

2020-09-08 07:43 UTC, HaseenaSainul requested changes

2020-09-08 07:43 UTC, HaseenaSainul commented on NetworkControl/NetworkControl.h
> +                    // Looks like the acknwledge did not get a reply, should we retry ?
typo error in comments 'acknwledge'

2020-09-08 07:43 UTC, HaseenaSainul commented on NetworkControl/NetworkControl.cpp
> +                    Core::JSON::ArrayType<Entry>::Iterator loop(storage.Elements());
Trying to keep Entry objects on Settings, since both are different.

2020-09-08 07:43 UTC, HaseenaSainul commented on NetworkControl/NetworkControl.cpp
>                      if (how == JsonData::NetworkControl::NetworkData::ModeType::MANUAL) {
Not keeping the Interface mode anywhere and trying to use it later on (example from RefreshDNS()

2020-09-08 07:43 UTC, HaseenaSainul commented on NetworkControl/NetworkControl.cpp
> +                if (loop->second.Info().Mode() == JsonData::NetworkControl::NetworkData::ModeType::DYNAMIC) {
Trying to use non stored value, hence this will fail to retrieve the DNS info received from the DHCP server

2020-09-08 07:53 UTC, pwielders commented on NetworkControl/NetworkControl.cpp
> +                    index->second.Discover(index->second.Info().Address());
This is part of the method Reload, this is only triggered if a REST call/JSONRPC call is coming trigegr this functionality, or during initialization, if this interface is configured for DHCP.
If your remark is, can we avoid during initialization a DHCP request for this interface, we can not, sonce we do not know what the lease period for this interface was, or is. To know the lease time, the Network control *must* execute a discovery.
Maybe we could make logic to check if the IP in there is the IP also found in the persistent store and if so, start with an Ack sequence, as an optimization. But lets do this optimization in a second run.

2020-09-08 07:55 UTC, pwielders commented on NetworkControl/NetworkControl.cpp
> +                validIP |= hasValidIP;
If there are no interfaces set in the required list, the network subsystem can be activated if any interface has a validIP address so in case the required list is empty, the subsystem is based on this falg. But I saw already that the setting of the Network SubSystem is not correct, so that it is not used might be a reason :-)

2020-09-08 07:59 UTC, pwielders commented on NetworkControl/NetworkControl.cpp
> +        fullSet &= (count == _requiredSet.size());
As stated above, I saw that there is something wrong in detecting the SubSystem logic. I need to revisit it. Thanks for this remark, casue it might well be the issue :-)

2020-09-08 08:01 UTC, pwielders commented on NetworkControl/DHCPClientImplementation.h
>              _adminLock.Unlock();
With what purpose? It will speed up the code sligtly but make the reading of it a bit more difficult. It would be a trade off between speed and readability. This is executed very rarely, but we could

2020-09-08 08:02 UTC, pwielders commented on NetworkControl/DHCPClientImplementation.cpp
> +                RemoteNode(BroadcastServerNode);
This is still work in progress,  as you can see there is still some commented out stuff, I think now it is already different,

2020-09-08 08:03 UTC, pwielders commented on NetworkControl/NetworkControl.cpp
> +                    Core::JSON::ArrayType<Entry>::Iterator loop(storage.Elements());
???

2020-09-08 08:10 UTC, HaseenaSainul commented on NetworkControl/NetworkControl.cpp
> +                    Core::JSON::ArrayType<Entry>::Iterator loop(storage.Elements());
Second field of map::info is Settings and we are trying to keep the type Entry type on thia (loop is type of Entry)

2020-09-09 14:29 UTC, HaseenaSainul approved these changes

2020-09-09 14:45 UTC, merged