Modified to fetch & build brcm specific code from external repository
rdkcentral/ThunderNanoServices pull request #216
Opened 2020-09-09 16:49 UTC by neeraj-deshpande

2020-09-22 11:59 UTC, MFransen69 submitted a review, later dismissed

2020-09-24 07:33 UTC, bramoosterhuis commented on CMakeLists.txt
> +option(CODE_FROM_EXTERNAL_REPOSITORY "Include code from External Repository" ON)
I would expect to switch this new feature default off and if everything is fine after a while switch it on.

2020-09-24 15:35 UTC, MFransen69 requested changes
Hi Neeraj, think I was not clear in my last request, sorry. It is not a special flag to override when to take the sources from Gerrit, the idea was that you could specify for a component to not take the sources from Gerrit (or RDK Central) but you could specify a folder to get the sources from (so you can have them local on a disk or something similar instead)

2020-09-28 06:53 UTC, MFransen69 approved these changes

2020-09-28 08:21 UTC, MFransen69 approved these changes

2020-09-29 07:41 UTC, merged