Added AMLogic implementation
rdkcentral/ThunderNanoServices pull request #275
Opened 2020-11-17 12:07 UTC by krp97

This commit introduces a reworked version of the DisplayInfo
implementation for an AMLogic hp40a platform. The notifications
about a state change of the connection are handled via
incoming udev messages.

TODO:
Currently, the udev state change messages are not being generated
on a succesfull authentication. For now this has been worked
around by checking the contents of the file with a timeout.
As this is not an optimal solution, the lack of udev messages
is being investigated. Tracking link:
https://jira.rdkcentral.com/jira/browse/HP40A-603

2020-11-17 13:04 UTC, pwielders requested changes
Most remarks are minor, but the IWebdriver to configure really requires an update :-)

2020-11-17 13:04 UTC, pwielders commented on DisplayInfo/DisplayInfo.cpp
> +        ASSERT(_hdrProperties != nullptr);
The RaspberryPi has no HDR properties and thus no implementation for this interface. It should still work, but this might kill it.

2020-11-17 13:04 UTC, pwielders commented on DisplayInfo/DisplayInfo.cpp
> +            Exchange::IWebDriver* configConnection = _connectionProperties->QueryInterface<Exchange::IWebDriver>();
Agree that you need an interface to configure some implementations, and this is good, but reusing an interface for the WebDriver is a bit debatable. Can you make a Generic IConfiguration interface, so that it is specific and easier to understand.

2020-11-19 13:43 UTC, pwielders commented
@mhughesacn Seems we have a black duck issue again :-) Can you guide us ?

2020-11-19 13:53 UTC, mhughesacn commented
Hi @pwielders - This was sorted yesterday and the check cleared.  (The problem was a misconfiguration in BlackDuck which I fixed as soon as I saw it.)

2020-11-24 07:44 UTC, pwielders commented
@mhughesacn Thanks !

2020-12-02 18:57 UTC, pwielders approved these changes

2020-12-02 19:09 UTC, merged