DIAL and DHCP Server: changed TRACE_LX to TRACE()
rdkcentral/ThunderNanoServices pull request #318
Opened 2020-12-21 11:27 UTC by HaseenaSainul

2020-12-21 20:03 UTC, pwielders approved these changes

2020-12-21 20:07 UTC, pwielders requested changes

2020-12-21 20:07 UTC, pwielders commented on DHCPServer/DHCPServer.cpp
> +            TRACE(Trace::Information, (_T("Could not create DHCPServer persistent path")));
Error ?

2020-12-21 20:07 UTC, pwielders commented on DHCPServer/DHCPServer.cpp
> +                TRACE(Trace::Information, (_T("Could not save leases in permanent storage area.\n")));
Error ?

2020-12-22 04:42 UTC, HaseenaSainul commented on DHCPServer/DHCPServer.cpp
> +            TRACE(Trace::Information, (_T("Could not create DHCPServer persistent path")));
done

2020-12-22 04:42 UTC, HaseenaSainul commented on DHCPServer/DHCPServer.cpp
> +                TRACE(Trace::Information, (_T("Could not save leases in permanent storage area.\n")));
done

2020-12-25 21:08 UTC, pwielders approved these changes

2020-12-25 21:23 UTC, merged