FirmareControl/FrontPanel/SystemdConnector: moved TRACE_LX to TRACE()
rdkcentral/ThunderNanoServices pull request #319
Opened 2020-12-21 12:19 UTC by HaseenaSainul

2020-12-21 20:05 UTC, pwielders requested changes

2020-12-21 20:05 UTC, pwielders commented on SystemdConnector/SystemdConnector.cpp
> +            TRACE(Trace::Information, (_T("Notify Nexus Server Ready to systemd: FAILED (%d)\n"), rc));
Maybe we should make this an Error ?

2020-12-21 20:05 UTC, pwielders commented on FileTransfer/FileTransfer.h
> +                            TRACE(Trace::Information, (_T("Invoke of inotify_rm_watch failed")));
Isn't this an Error ?

2020-12-22 04:49 UTC, HaseenaSainul commented on SystemdConnector/SystemdConnector.cpp
> +            TRACE(Trace::Information, (_T("Notify Nexus Server Ready to systemd: FAILED (%d)\n"), rc));
done

2020-12-22 04:50 UTC, HaseenaSainul commented on FileTransfer/FileTransfer.h
> +                            TRACE(Trace::Information, (_T("Invoke of inotify_rm_watch failed")));
done

2020-12-25 21:06 UTC, pwielders approved these changes

2020-12-25 21:21 UTC, merged