Fix DIAL additionaldataUrl port settings
rdkcentral/ThunderNanoServices pull request #349
Opened 2021-01-28 09:10 UTC by Damian-Danylko

2021-01-28 12:37 UTC, pwielders commented on DIALServer/DIALServer.cpp
> -            _webServerPort = _dialURL.Port();
Tgis looks scary, now the _webServerPort is not set. PLease double check if this is really good.

2021-01-28 12:37 UTC, pwielders commented on DIALServer/DIALServer.cpp
> +            const string additionalDataUrl = (_T("http://localhost") + ((_webServerPort == 80)? _T("") : _T(":") + Core::NumberType<uint16_t>(_webServerPort).Text()) + _T("/Service/DIALServer/Apps/")
This I understand and indeed is a bug. Good Fix

2021-01-28 12:38 UTC, pwielders requested changes
Please double check the removal of the _webServerPort. I think it is an accidental remove and it should be in

2021-01-28 15:00 UTC, Damian-Danylko commented on DIALServer/DIALServer.cpp
> -            _webServerPort = _dialURL.Port();
I forgot to commint header file. Now implementation should cover both case when WebServer is off and on. In both cases 
_webServerPort will be set properly.

2021-01-29 16:45 UTC, pwielders approved these changes

2021-01-29 16:45 UTC, merged