[ResourceMonitor] Refactored plugin
rdkcentral/ThunderNanoServices pull request #352
Opened 2021-02-09 15:43 UTC by lukiwa

ResourceMonitor is now able to monitor processes individually (WPEFramework, WPEProcess, WPENetworkProcess, etc) and all together (select name "WPE" for monitoring all WPE related processes) and collects information about memory usage, and puts it into a .csv file. Switched to RAII containers where possible. Changed GCC __builtin_popcount function to STL equivalent. Tested on RPI and inside a docker container.

2021-02-10 10:16 UTC, krp97 requested changes
I'd like to discuss some minor changes, let me know what you think about them and please retest after applying all valid resolutions.

PS: Before you apply any fixes, could you align this branch with master? I think it has gone out of date.

2021-02-10 10:16 UTC, krp97 commented on ResourceMonitor/ResourceMonitorImplementation.cpp
> +            uint32_t CountSetBits(const bool calculateUSS, const std::vector<uint32_t>& pageBuffer, const std::vector<uint32_t>& inverseMask)
I think we could refactor this somehow, because `CountSetBits` is essentially two functions where we trigger one or the other based on some arbitrary flag.

This:
```
 else {
   for (uint32_t index = 0; index < _bufferEntries; index++) {
     count += std::bitset < 32 > (pageBuffer[index]).count();
   }
 }
```
could be reworked into something like:
```
std::accumulate(pageBuffer.begin(), pageBuffer.end(), 0, [](int total, uint32_t page) {
    return total + std::bitset<32>(page).count();
})
```

This:
```
if (calculateUSS) {
  for (uint32_t index = 0; index < _bufferEntries; index++) {
    count += std::bitset < 32 > (pageBuffer[index] & (~inverseMask[index])).count();
  }
}
```
could potentially be replaced with:
```
[](const std::vector<uint32_t>& pageBuffer, const std::vector<uint32_t>& inverseMask){
    uint32_t count = 0;
    for (uint32_t index = 0; index < _bufferEntries; index++) {
         count += std::bitset < 32 > (pageBuffer[index] & (~inverseMask[index])).count();
    }
}
```
Especially since I think they're only used once in the `LogProcess` function. You could also just split this into two seperate functions and name them appropriately. 

Just a suggestion, let me know what you think.

2021-02-10 10:16 UTC, krp97 commented on ResourceMonitor/ResourceMonitorImplementation.cpp
> +            std::vector<uint32_t> _otherMap; // Buffer used to mark other processes pages.
This name could use some refactoring, `_otherMap` doesn't give the reader any insight.

2021-02-23 08:08 UTC, lukiwa commented
After diving deeper into the results returned by the measurements I decided to change the underlying measurement algorithm. More to be read here: https://github.com/rdkcentral/Thunder/pull/482

2021-02-23 13:23 UTC, lukiwa commented
I messed something with rebases, closing this PR.

2021-02-23 13:23 UTC, closed without merging