[METROL 236] HDR luminance adjustment possibility
rdkcentral/ThunderNanoServices pull request #376
Opened 2021-03-25 11:29 UTC by lukiwa

https://github.com/rdkcentral/ThunderInterfaces/pull/36

2021-03-25 12:28 UTC, pwielders requested changes

2021-03-25 12:28 UTC, pwielders commented on Compositor/Compositor.h
> +            Core::JSON::DecUInt16 Brightness;
Why not define the enum? Looks like the setting (on interface) is an enum, Lets reflect that in the config

2021-03-25 12:28 UTC, pwielders commented on Compositor/Compositor.h
> +            Core::JSON::DecUInt16 Brightness;
Where is the config actually being used ? ohh this isreporting on it. Would also expect that you can set it form the config, so I ghuess it is still missing ?

2021-03-25 12:44 UTC, lukiwa commented on Compositor/Compositor.h
> +            Core::JSON::DecUInt16 Brightness;
This is actually leftover from the abandoned HTTP response functionality that I planned to add, it should be deleted. You can set the brightness setting from the config in the Compositor-brcm (https://github.com/WebPlatformForEmbedded/Compositor-brcm/pull/1)

2021-03-29 07:52 UTC, pwielders commented on Compositor/Compositor.cpp
> +        const WPEFramework::Exchange::IComposition* constComposition = _composition;
What is the added value of copying the pointer ? if the issue is at the executions you can also state there:
return (static_cast<const Exchange::IComposition*>(_composition)->SdrToHdrGraphicsBrightness(brightness));
but I think that is not even nessecary :-)

2021-03-29 10:59 UTC, lukiwa commented on Compositor/Compositor.cpp
> +        const WPEFramework::Exchange::IComposition* constComposition = _composition;
Copying is not necessary indeed, but the cast itself should remain IMO. Those are warnings I got when I remove it (and get method is calling the not-const method from the interface without them):
```
warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
             return _composition->SdrToHdrGraphicsBrightness(brightness);
                                                                       ^
In file included from Compositor.h:24:0,
                 from Compositor.cpp:20:
../../../host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/WPEFramework/interfaces/IComposition.h:95:26: note: candidate 1: virtual uint32_t WPEFramework::Exchange::IComposition::SdrToHdrGraphicsBrightness(const WPEFramework::Exchange::IComposition::Brightness&)
         virtual uint32_t SdrToHdrGraphicsBrightness(const Brightness& brightness) = 0;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../../host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/WPEFramework/interfaces/IComposition.h:94:26: note: candidate 2: virtual uint32_t WPEFramework::Exchange::IComposition::SdrToHdrGraphicsBrightness(WPEFramework::Exchange::IComposition::Brightness&) const
         virtual uint32_t SdrToHdrGraphicsBrightness(Brightness& brightness /* @out */) const = 0;
```

2021-03-29 15:30 UTC, pwielders approved these changes

2021-04-06 10:21 UTC, lukiwa commented
Changes implementation due to changes in the interface

2021-04-08 07:29 UTC, pwielders approved these changes

2021-04-09 10:49 UTC, merged