DHCPServer: config update
rdkcentral/ThunderNanoServices pull request #409
Opened 2021-04-29 08:56 UTC by HaseenaSainul

2021-04-29 10:14 UTC, artur-gebicz-ml requested changes

2021-04-29 10:14 UTC, artur-gebicz-ml commented on DHCPServer/CMakeLists.txt
> +set(PLUGIN_DHCPSERVER_AUTOSTART false CACHE STRING true)
Set is missing the description. It shouldn't be 'true', but something meaningful

2021-04-29 13:51 UTC, HaseenaSainul commented on DHCPServer/CMakeLists.txt
> +set(PLUGIN_DHCPSERVER_AUTOSTART false CACHE STRING true)
updated

2021-05-03 06:34 UTC, pwielders submitted a review, later dismissed

2021-05-04 07:00 UTC, artur-gebicz-ml requested changes

2021-05-04 10:57 UTC, HaseenaSainul commented on DHCPServer/CMakeLists.txt
> +set(PLUGIN_DHCPSERVER_AUTOSTART false CACHE STRING "Automatically start DHCPServer plugin")
done

2021-05-04 10:57 UTC, HaseenaSainul commented on DHCPServer/CMakeLists.txt
> +set(PLUGIN_DHCPSERVER_OUTOFPROCESS true CACHE BOOL "Controls if the plugin should run in its own process [true, false].")
done

2021-05-04 11:18 UTC, artur-gebicz-ml approved these changes

2021-05-04 12:12 UTC, merged