Svalbard: config update
rdkcentral/ThunderNanoServices pull request #424
Opened 2021-05-03 07:23 UTC by HaseenaSainul

2021-05-03 14:28 UTC, bramoosterhuis submitted a review, later dismissed

2021-05-04 11:16 UTC, artur-gebicz-ml requested changes

2021-05-04 11:16 UTC, artur-gebicz-ml commented on Svalbard/Svalbard.config
> -    if(PLUGIN_SVALBARD_OOP)
I believe we should make that backward compatible, so if PLUGIN_SVALBARD_OOP then set the PLUGIN_SVALBARD_OUTOFPROCESS to true

2021-05-04 12:11 UTC, HaseenaSainul commented on Svalbard/Svalbard.config
> -    if(PLUGIN_SVALBARD_OOP)
What I understood from @pwielders is that this module is not yet used by any clients. So I think it safe to change the config now. @bramoosterhuis can you please confirm

2021-05-13 07:35 UTC, pwielders commented on Svalbard/Svalbard.config
> -    if(PLUGIN_SVALBARD_OOP)
@artur-gebicz-ml  good point but indeed @HaseenaSainul is right here, there is no need for backwards compatibility since this has not been deployed, no need for backwards compatibility.

2021-05-13 07:38 UTC, pwielders approved these changes

2021-05-17 10:15 UTC, merged