Make HDCP level configurable for RPI Platform
rdkcentral/ThunderNanoServices pull request #468
Opened 2021-09-01 11:14 UTC by sramani-metro

2021-09-02 12:29 UTC, MFransen69 requested changes

2021-09-02 12:29 UTC, MFransen69 commented on DisplayInfo/RPI/PlatformImplementation.cpp
> +            Core::JSON::String hdcpLevel;
Couldn't we better use Core::JSON::EnumType<> ?

2021-09-02 12:29 UTC, MFransen69 commented on DisplayInfo/RPI/PlatformImplementation.cpp
> +    Config _config;
Is there actually a reason to store the config for now? We already store the parse result in _value correct?

2021-09-02 12:42 UTC, sramani-metro commented on DisplayInfo/RPI/PlatformImplementation.cpp
> +            Core::JSON::String hdcpLevel;
I thought having a string in the config file would help understand what it means. But yes, We could.

2021-09-02 12:43 UTC, sramani-metro commented on DisplayInfo/RPI/PlatformImplementation.cpp
> +    Config _config;
You are right. We dont need to store it at this time. I will change this

2021-09-02 12:50 UTC, MFransen69 commented on DisplayInfo/RPI/PlatformImplementation.cpp
> +            Core::JSON::String hdcpLevel;
The result for the config file itself would be the same. It is the implementation here that is easier to do (e.g. with support for the conversions etc)

2021-09-02 15:30 UTC, sramani-metro commented on DisplayInfo/RPI/PlatformImplementation.cpp
> +            Core::JSON::String hdcpLevel;
Yes, it is better to use existing enum conversions. It does simplify the implementation by a great deal. Pushed new commit.

2021-09-06 12:20 UTC, MFransen69 approved these changes

2021-09-13 05:15 UTC, merged