Weston: Compositor integration
rdkcentral/ThunderNanoServices pull request #472
Opened 2021-09-07 14:41 UTC by HaseenaSainul

2021-09-13 06:34 UTC, pwielders requested changes

2021-09-13 06:34 UTC, pwielders commented on Compositor/lib/Wayland/Wayland.cpp
> +            , _active(false)
I think this _active has no added value. From what I see in the usage, you can just, in the destructor,  do _job.Stop()  and than _job.Wait(STOPPED, Core::inifinite). This will make sure that the thread is "stopped".

2021-09-13 11:27 UTC, HaseenaSainul commented on Compositor/lib/Wayland/Wayland.cpp
> +            , _active(false)
thanks @pwielders for the comment, will check

2021-09-14 07:49 UTC, HaseenaSainul commented on Compositor/lib/Wayland/Wayland.cpp
> +            , _active(false)
Updated the code as per comments

2021-09-14 08:05 UTC, pwielders submitted a review, later dismissed

2021-09-14 17:14 UTC, pwielders approved these changes

2021-09-15 04:35 UTC, merged