Dev/wificontrol wps
rdkcentral/ThunderNanoServices pull request #515
Opened 2021-11-25 11:07 UTC by sramani-metro

2021-11-30 10:24 UTC, pwielders requested changes
Looks good! Just would like to improve a bit on the constness, minor issues but just to make it more consistent with the remainder of the code.

2021-11-30 10:24 UTC, pwielders commented on WifiControl/Controller.h
> +            bool Credentials() {
I got a feeling a lot of the following methods can be made const :-)
bool Credentials() const;
bool Active() const;
(const) string NetworkKey() const;
(const) string SSID() const;
WPASupplicant::Network::wpsauthtypes AuthType() const;

2021-11-30 10:24 UTC, pwielders commented on WifiControl/Controller.h
> +                Core::CriticalSection _adminLock;
And if you make those methods const, make the _adminLock mutable so it compiles ;-)

2021-11-30 10:24 UTC, pwielders commented on WifiControl/Controller.h
> +        inline uint32_t GetWpsCredentials(string& SSID, string& NetworkKey, WPASupplicant::Network::wpsauthtypes& AuthType ) {
If all the others are const, this can become const as well. In this class the CS is already mutable..

2021-11-30 10:24 UTC, pwielders commented on WifiControl/WifiControl.h
> +            ~WpsConnect()
YYou are allowed to use the default feature, it is part of std C++11, old code might not be using it because it was written prior to the C++11 feature turned on. No need to chaange but just for the next time :-)

2021-11-30 10:24 UTC, pwielders commented on WifiControl/WifiControl.h
> +            WpsConnect(WifiControl& parent, Core::ProxyType<WPASupplicant::Controller>& controller)
I really love as much as posisble const :-) so this could be: 
WpsConnect(WifiControl& parent, const Core::ProxyType<WPASupplicant::Controller>& controller)

2021-11-30 10:24 UTC, pwielders commented on WifiControl/WifiControl.h
> +            uint32_t Invoke(const string ssid, const JsonData::WifiControl::ConnectParamsData::AutoconnectType actype, const string pin, uint32_t walkTime) {
And I guess this signature should be:
uint32_t Invoke(const string& ssid, const JsonData::WifiControl::ConnectParamsData::AutoconnectType actype, const string& pin, const uint32_t walkTime)
On the last one (const uint32_t) technically it does not add any value, it is just for clarity. agree.

2021-11-30 10:24 UTC, pwielders commented on WifiControl/WifiControl.h
> +            bool Active() {
I guess:
bool Active() const; and bool Credentials() const; ?

2021-12-02 12:07 UTC, sramani-metro commented on WifiControl/Controller.h
> +            bool Credentials() {
Done

2021-12-02 12:08 UTC, sramani-metro commented on WifiControl/Controller.h
> +                Core::CriticalSection _adminLock;
Done

2021-12-02 12:08 UTC, sramani-metro commented on WifiControl/Controller.h
> +        inline uint32_t GetWpsCredentials(string& SSID, string& NetworkKey, WPASupplicant::Network::wpsauthtypes& AuthType ) {
Done

2021-12-02 12:08 UTC, sramani-metro commented on WifiControl/WifiControl.h
> +            ~WpsConnect()
Done

2021-12-02 12:08 UTC, sramani-metro commented on WifiControl/WifiControl.h
> +            WpsConnect(WifiControl& parent, Core::ProxyType<WPASupplicant::Controller>& controller)
Done

2021-12-02 12:08 UTC, sramani-metro commented on WifiControl/WifiControl.h
> +            uint32_t Invoke(const string ssid, const JsonData::WifiControl::ConnectParamsData::AutoconnectType actype, const string pin, uint32_t walkTime) {
Done

2021-12-02 12:08 UTC, sramani-metro commented on WifiControl/WifiControl.h
> +            bool Active() {
Done

2021-12-02 19:50 UTC, pwielders approved these changes

2021-12-02 20:42 UTC, merged