DIALServer: Read DeviceId from the subsystem
rdkcentral/ThunderNanoServices pull request #538
Opened 2022-01-27 15:14 UTC by HaseenaSainul

2022-02-01 16:20 UTC, pwielders commented on DIALServer/DIALServer.h
> +            PluginHost::ISubSystem* subSystem = _service->SubSystems();
Be carefull, this is a leak. If you get the subSystem, it is an addref'ed interface make sure you release it!

2022-02-02 05:20 UTC, HaseenaSainul commented on DIALServer/DIALServer.h
> +            PluginHost::ISubSystem* subSystem = _service->SubSystems();
done

2022-02-02 08:40 UTC, pwielders requested changes

2022-02-02 08:40 UTC, pwielders commented on DIALServer/DIALServer.h
> +            PluginHost::ISubSystem* subSystem = _service->SubSystems();
Sorry, not completly, it is still leaking if the subsystem is retrieved (not a nullptr), it is addref'ed but if the SubSystem->IsActive() == false, it never gets released and thus it is leaking.. Suggest t remove the IsActive check from the equation and it is good to go...

2022-02-02 08:43 UTC, pwielders requested changes
It is still leaking if the system is not active, suggest to remove the IsActive call or split the if..

2022-02-02 09:04 UTC, HaseenaSainul commented on DIALServer/DIALServer.h
> +            PluginHost::ISubSystem* subSystem = _service->SubSystems();
done

2022-02-02 09:04 UTC, HaseenaSainul commented
IsActive check is removed

2022-02-02 09:55 UTC, pwielders approved these changes

2022-02-02 09:56 UTC, merged