AVS: plugin adding from standalone repo to Thundernanoservices
rdkcentral/ThunderNanoServices pull request #544
Opened 2022-02-17 08:45 UTC by HaseenaSainul

2022-02-17 11:12 UTC, artur-gebicz-ml requested changes
Generally looks good. Only one thing to fix or add some description why it has been done like that

2022-02-18 08:09 UTC, artur-gebicz-ml approved these changes
LGTM

2022-02-22 13:40 UTC, pwielders approved these changes

2022-02-22 13:57 UTC, HaseenaSainul commented on AVS/Impl/AVSDevice/AVSDevice.cpp
> +        alexaClientSDK::avsCommon::utils::logger::LoggerSinkManager::instance().initialize(alexaClientSDK::avsCommon::utils::logger::ConsoleLogger::instance());
done

2022-02-22 14:39 UTC, merged