Test App: StoreTest added to test Performance of PersistentStore and Dictionary plugin via JSONRPC, ReST and COMRPC channels
rdkcentral/ThunderNanoServices pull request #570
Opened 2022-03-29 04:58 UTC by HaseenaSainul

2022-03-29 06:21 UTC, MFransen69 requested changes

2022-03-29 06:21 UTC, MFransen69 commented on examples/StoreTest/StoreTest.cpp
> +class PersistentStore : public Thunder::JSONRPC::SmartLinkType<Thunder::Core::JSON::IElement> {
If we are going to put this in examples people will consider this code that reflects correctly how things should be done and will copy this code as a starting point. So either we will make it so and use JSONRPC::LinkType (see the jsonrpocclient example) and certainly not JsonObject (which is not allowed in ML code) or we just put this code next to our unittest and other test code. (perhaps the latter is a better approach all together). I think it is more of a test then an example, it is also called StoreTest :) so I guess better to out it with the tests

2022-03-29 06:21 UTC, MFransen69 commented on examples/StoreTest/StoreTest.cpp
> +    virtual ~StorePerformance() = default;
why is this virtual? Perhaps I missed it but there does not seem to be any virtual method

2022-03-29 06:21 UTC, MFransen69 commented on examples/StoreTest/StoreTest.cpp
> +    ~Dictionary()
nitpicking I guess, but it should be overriden, please also check below (if we put it in examples it should be rather correct)

2022-03-29 06:21 UTC, MFransen69 commented on examples/StoreTest/StoreTest.cpp
> +    void Operational(const bool upAndRunning)
think this is an override as well (also check below)

2022-03-29 06:26 UTC, HaseenaSainul commented on examples/StoreTest/StoreTest.cpp
> +class PersistentStore : public Thunder::JSONRPC::SmartLinkType<Thunder::Core::JSON::IElement> {
Ok, Will move this to unit tests folder

2022-03-29 06:26 UTC, HaseenaSainul commented on examples/StoreTest/StoreTest.cpp
> +    virtual ~StorePerformance() = default;
will correct

2022-03-29 06:27 UTC, HaseenaSainul commented on examples/StoreTest/StoreTest.cpp
> +    ~Dictionary()
will check

2022-03-29 06:27 UTC, HaseenaSainul commented on examples/StoreTest/StoreTest.cpp
> +    void Operational(const bool upAndRunning)
will check

2022-03-29 07:16 UTC, HaseenaSainul commented on examples/StoreTest/StoreTest.cpp
> +class PersistentStore : public Thunder::JSONRPC::SmartLinkType<Thunder::Core::JSON::IElement> {
I changed JsonObject to JSON::Container based class based on Parameter and Response requirement.
I used JSONRPC::SmartLinkType instead JSONRPC::LinkType to get the plugin activated/deactivated status to return proper states from IsOperational() method.

2022-03-29 07:19 UTC, HaseenaSainul commented on examples/StoreTest/StoreTest.cpp
> +class PersistentStore : public Thunder::JSONRPC::SmartLinkType<Thunder::Core::JSON::IElement> {
Will move this to Thunder as next step :)

2022-03-29 14:05 UTC, HaseenaSainul commented on examples/StoreTest/StoreTest.cpp
> +class PersistentStore : public Thunder::JSONRPC::SmartLinkType<Thunder::Core::JSON::IElement> {
Moved StoreTest to tests

2022-03-31 06:49 UTC, MFransen69 approved these changes

2022-03-31 07:10 UTC, merged