Implementing Suspend and Resume for webserver
rdkcentral/ThunderNanoServices pull request #576
Opened 2022-04-26 11:47 UTC by Karthick-Somasundaresan

2022-07-12 08:08 UTC, pwielders requested changes
There is a race condition in the code that requires some attention.

2022-07-12 08:08 UTC, pwielders commented on WebServer/WebServerImplementation.cpp
> +            PluginHost::IStateControl::state state;
Minor, no need to change but for these short construction it is oke to use the Core::SafeSync<Core::CriticalSection> lock(_adminLock);

2022-07-12 08:08 UTC, pwielders commented on WebServer/WebServerImplementation.cpp
> +            for (auto & observer: _observers){
There is no need to do this. Better would be to ASSERT to indicate a potential memory leak and then do run through the observeers, but only Release() the interface(), although that will probably nolonger work :-)

2022-12-21 14:05 UTC, MFransen69 commented
We'll pick this up in the future again, lower priority for now

2022-12-21 14:05 UTC, closed without merging