ResourceMonitor: set CSVFile Path to read values from CompileMemoryCsv
rdkcentral/ThunderNanoServices pull request #623
Opened 2022-08-24 04:39 UTC by HaseenaSainul

2022-08-25 13:36 UTC, lukiwa approved these changes

2022-08-25 13:47 UTC, pwielders requested changes

2022-08-25 13:47 UTC, pwielders commented on ResourceMonitor/ResourceMonitorImplementation.cpp
> +            if (config.Path.IsSet()) {
Can we, by default, prefix the given name ( or the default name) with Service->VolatilePath. If the system is configured to have the temporary filesystem configured somewhere else than /temp, it still works as expected :-)

2022-08-25 14:41 UTC, HaseenaSainul commented on ResourceMonitor/ResourceMonitorImplementation.cpp
> +            if (config.Path.IsSet()) {
Sure, will update :)

2022-08-27 10:28 UTC, pwielders approved these changes

2022-08-27 10:33 UTC, merged