Modified Compositor plugin to use Python config generator.
rdkcentral/ThunderNanoServices pull request #633
Opened 2022-09-12 09:24 UTC by neeraj-deshpande

2022-09-16 06:41 UTC, sramani-metro requested changes

2022-09-16 06:41 UTC, sramani-metro commented on Compositor/Compositor.conf.in
> +    if "@PLUGIN_COMPOSITOR_PAK_PATH@":
I suspect if these config options are not set, you will see errors from config generator. Mainly because, if these configs are not set, you are essentially doing a check like

if "":
   configuration.add()

Ideally, you shouldnt be needing the if condition. the add() will add the config only if it is defined non-empty.

2022-09-16 06:41 UTC, sramani-metro commented on Compositor/Compositor.conf.in
> +    if int("@PLUGIN_COMPOSITOR_HARDWAREREADY@") > 0:
Is this suppose to work as a boolean or an integer value? if it is a boolean then, lets use boolean().

2022-09-16 08:56 UTC, neeraj-deshpande commented on Compositor/Compositor.conf.in
> +    if int("@PLUGIN_COMPOSITOR_HARDWAREREADY@") > 0:
It is integer e.g. 3

2022-09-16 13:53 UTC, neeraj-deshpande commented on Compositor/Compositor.conf.in
> +    if "@PLUGIN_COMPOSITOR_PAK_PATH@":
Done.

2022-09-19 06:20 UTC, sramani-metro approved these changes

2022-09-22 12:02 UTC, merged