Modified NetworkControl plugin to use Python config generator.
rdkcentral/ThunderNanoServices pull request #635
Opened 2022-09-13 03:46 UTC by neeraj-deshpande

2022-09-13 09:31 UTC, HaseenaSainul approved these changes

2022-09-13 11:00 UTC, sramani-metro requested changes

2022-09-15 08:58 UTC, neeraj-deshpande commented on NetworkControl/NetworkControl.conf.in
> +            interface_config = {}
Done.

2022-09-22 12:15 UTC, pwielders approved these changes

2022-09-22 12:20 UTC, bramoosterhuis approved these changes

2022-09-23 06:30 UTC, sramani-metro approved these changes

2022-09-23 07:37 UTC, HaseenaSainul approved these changes

2022-09-23 07:37 UTC, merged