Modified WebServer plugin to use Python config generator.
rdkcentral/ThunderNanoServices pull request #638
Opened 2022-09-13 07:23 UTC by neeraj-deshpande

2022-09-13 09:47 UTC, HaseenaSainul approved these changes

2022-09-13 10:55 UTC, sramani-metro requested changes

2022-09-13 10:55 UTC, sramani-metro commented on WebServer/WebServer.conf.in
> +        proxy_config = {}
Let's avoid using Python dictionary directly. Instead use the JSON() object in the inner level too. That way it provides a consistent reference for future implementations.

2022-09-13 10:55 UTC, sramani-metro commented on WebServer/WebServer.conf.in
> +        proxy_config = {}
Look at https://github.com/WebPlatformForEmbedded/ThunderNanoServicesRDK/blob/dev/conf-gen/OpenCDMi/OCDM.conf.in

2022-09-15 08:02 UTC, neeraj-deshpande commented on WebServer/WebServer.conf.in
> +        proxy_config = {}
Done.

2022-09-16 06:50 UTC, sramani-metro approved these changes

2022-09-22 12:27 UTC, merged