Modified BackOffice plugin to use Python config generator.
rdkcentral/ThunderNanoServices pull request #651
Opened 2022-09-26 09:17 UTC by neeraj-deshpande

2022-09-26 09:21 UTC, sramani-metro requested changes

2022-09-26 09:21 UTC, sramani-metro commented on BackOffice/BackOffice.conf.in
> +if "@PLUGIN_BACKOFFICE_CALLSIGN_MAPPING@":
Do you need this if?

2022-09-26 10:20 UTC, neeraj-deshpande commented on BackOffice/BackOffice.conf.in
> +if "@PLUGIN_BACKOFFICE_CALLSIGN_MAPPING@":
Yes. The split() below is generating empty list which gets added to the output json.

2022-09-26 12:08 UTC, neeraj-deshpande commented on BackOffice/BackOffice.conf.in
> +if "@PLUGIN_BACKOFFICE_CALLSIGN_MAPPING@":
Done.

2022-09-27 05:30 UTC, sramani-metro approved these changes

2022-09-30 11:24 UTC, merged