Development/mesa compositor
rdkcentral/ThunderNanoServices pull request #708
Opened 2023-03-09 05:17 UTC by bramoosterhuis

2023-03-09 14:55 UTC, mhughesacn requested changes
Hi Bram,
Real code matches were detected here - please see my review comments.
Thank you,
Martin Hughes, RDK CMF Compliance Team

2023-03-09 14:55 UTC, mhughesacn commented on Compositor/lib/Mesa/include/CompositorTypes.h
> +    /*
The comment at 86-94 matches widely, but no actual code match.  Please change l.87 to:
Format Modifiers:
(from drm_fourcc.h, Copyright 2011 Intel Corporation (MIT Licensed))

and append to top level NOTICE:
Copyright 2011 Intel Corporation
Licensed under the MIT License

And append an MIT license to LICENSE (using the generic fields  for YEAR and COPYRIGHT HOLDER)

2023-03-09 14:55 UTC, mhughesacn commented on Compositor/lib/Mesa/renderer/src/GL/EGL.h
> +        inline static bool RestoreContext(const EglContext& context)
Unless you wrote this and wlroots took it from you, then lines 100
-109 are from https://github.com/swaywm/wlroots/tree/master/render and need a credit.  Please add before line 100:

Copyright (c) 2017, 2018 Drew DeVault
Copyright (c) 2014 Jari Vetoniemi
Licensed under the MIT License

And append the same lines to NOTICE.

And append an MIT license to LICENSE (keeping generic fields for YEAR and COPYRIGHT), if not already added from another comment.

2023-03-09 14:55 UTC, mhughesacn commented on Compositor/lib/Mesa/backend/src/DRM/DrmMonitor.h
> +            if (cards != nullptr) {
Appears to be derived from wlroots as in EGL.h comment.  If so, please add a similar credit before line 162:  (If not borrowing from wlroots, then you need to explain the exact match of the comment at line 180.)

Based on code from:
Copyright (c) 2017, 2018 Drew DeVault
Copyright (c) 2014 Jari Vetoniemi
Licensed under the MIT License

NOTICE & LICENSE changes already noted in EGL.h

2023-03-09 14:55 UTC, mhughesacn commented on Compositor/lib/Mesa/renderer/src/GL/RenderAPI.h
> +#define CASE_STR(value) \
Are lines 244-270 original?  Protex finds one match.  However, the code is very boilerplate (just a list of EGL errors) and a macro which is a straightforward use of the C++ preprocessor.  So easier to rewrite: Please rename to CASE_TO_STRING or similar and add a comment on line 243 to say you are using the stringification operator.

2023-03-09 14:55 UTC, mhughesacn commented on Compositor/lib/Mesa/backup/Mesa-working.cpp
> +#define CASE_STR(value) \
Same comments as in RendererAPI.h

2023-03-14 16:12 UTC, bramoosterhuis commented on Compositor/lib/Mesa/include/CompositorTypes.h
> +    /*
I removed the comment and point the reader to to the drm_fourcc.h header to find the details.

2023-03-14 16:12 UTC, bramoosterhuis commented on Compositor/lib/Mesa/renderer/src/GL/RenderAPI.h
> +#define CASE_STR(value) \
Fixed

2023-03-14 16:19 UTC, bramoosterhuis commented on Compositor/lib/Mesa/backend/src/DRM/DrmMonitor.h
> +            if (cards != nullptr) {
This header is a left over of a test, it's not used therefore I deleted the file.

2023-03-14 18:55 UTC, bramoosterhuis commented on Compositor/lib/Mesa/renderer/src/GL/EGL.h
> +        inline static bool RestoreContext(const EglContext& context)
I introduced a C++ object to save and restore the EGL context, it also works a bit more easier that the C-ish way.

2023-03-15 10:50 UTC, mhughesacn approved these changes
Hi Bram: Thank you for making the changes.  Blackduck is happy!

2023-03-16 07:50 UTC, merged