Register/Unregister: ensure sink exists in the list or not before registering and unregistering
rdkcentral/ThunderNanoServices pull request #786
Opened 2024-04-03 16:50 UTC by HaseenaSainul

2024-04-05 09:45 UTC, pwielders requested changes

2024-04-05 09:45 UTC, pwielders commented on NetworkControl/NetworkControlImplementation.cpp
> +            if (notification) {
Lets apply the same pattern on Register/Unregister everywhere. We ASSERT in debug on notification == nullptr, but after that we do insert it. This one is deviating from it. 
1) Or all registers we check for ((<notificaition> != nullptr) && (<iterator> == <list>.end())) { Register() }
2) Or all registers only on (<iterator> == <list>.end())
To be honoust as we check on already "registered", I think it is usefull to *also* check for nullptr, but that is currently more work so can also live with option 2 ;-) But lets not mix :-)

2024-04-05 09:45 UTC, pwielders commented on NetworkControl/NetworkControlImplementation.cpp
> +            if (notification) {
See above, this is deviating from what all the others did....

2024-04-08 05:10 UTC, HaseenaSainul commented on NetworkControl/NetworkControlImplementation.cpp
> +            if (notification) {
updated

2024-04-08 05:10 UTC, HaseenaSainul commented on NetworkControl/NetworkControlImplementation.cpp
> +            if (notification) {
done

2024-04-17 15:30 UTC, pwielders approved these changes

2024-04-21 10:31 UTC, merged